#+TITLE: DOCT notes
#+archive: %s_archive::datetree/
* Bugs :bug:
* Documentation :documentation:
* Optimizations :optimization:
* Features :feature:
** TODO add doct-unload-function
remove installed hooks
https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html
https://www.gnu.org/software/emacs/manual/html_node/elisp/Unloading.html#Unloading
* Enhancements :enhancement:
** IDEA doct--type-check take pair as first arg? Returns pair if succesful
May reduce verbosity when using doct--first-in...
** IDEA [[file:~/.emacs.d/straight/repos/doct/doct.el::defun doct--maybe-warn (keyword value &optional prefix][generalize this to accept warning string and args]]
* Miscellaneous :misc:
Unload byte compiled file loaded by straight.el when developing
#+begin_src emacs-lisp :results silent
(when (featurep 'doct)
  (unload-feature 'doct t))
(load-file "~/.emacs.d/straight/repos/doct/doct.el")
#+end_src
** RESEARCH [[file:~/.emacs.d/straight/repos/doct/doct.el::defun doct--constraint-rule-list (constraint value][why do we only need eval in one case?]]
Both macros return lambdas...
** RESEARCH do we need to depend on org-capture?
only thing we're using is org-capture-plist at runtime.
org-capture is loaded by then.
we also add to: org-capture-hooks, org-capture-contexts

Ok to defvar these before org-capture loaded?
