#+TITLE: DOCT notes
#+archive: %s_archive::datetree/
* Bugs :bug:
** RESEARCH overlapping captures & doct-get?
Should utilize [[help:org-capture-get][org-capture-get]] with the LOCAL parameter to avoid conflict between multiple capture processes.
I haven't run into any problems, but I do not often have multiple overlapping captures.
* Documentation :documentation:
* Optimizations :optimization:
* Features :feature:
* Enhancements :enhancement:
** IDEA doct--type-check take pair as first arg? Returns pair if succesful
May reduce verbosity when using doct--first-in...
** IDEA [[file:~/.emacs.d/straight/repos/doct/doct.el::defun doct--maybe-warn (keyword value &optional prefix][generalize this to accept warning string and args]]
** DONE make :doct proper plist
CLOSED: [2020-03-13 Fri 13:02]
just add description as :doct-name?
You can rebuild without that property in errors/warnings if necessary.
Then %doct(doct-name) would allow introspection of org-plist :description.
* Miscellaneous :misc:
Unload byte compiled file loaded by straight.el when developing
#+begin_src emacs-lisp :results silent
(when (featurep 'doct)
  (unload-feature 'doct t))
(load-file "~/.emacs.d/straight/repos/doct/doct.el")
#+end_src
** RESEARCH [[file:~/.emacs.d/straight/repos/doct/doct.el::defun doct--constraint-rule-list (constraint value][why do we only need eval in one case?]]
Both macros return lambdas...
** RESEARCH do we need to depend on org-capture?
only thing we're using is org-capture-plist at runtime.
org-capture is loaded by then.
we also add to: org-capture-hooks, org-capture-contexts

Ok to defvar these before org-capture loaded?
